### PR TITLE
Add skip argument to search funcs

### PR DESCRIPTION
**Pull request by jlumpe**
Add `skip` argument to `find` and `find_nearest`, which is a callback `f(i::Int)::Bool` indicating whether to exclude data point with index `i` from the results.

Tests require #5 be merged first.

### CODE REVIEW

**Comment by altre** [comment]
I'm not sure if this is a good thing to include in the API. Can't you just filter the result? Or do you have a special use case?

**Comment by jlumpe** [comment]
For `find` you can definitely just filter the result. `find_nearest` is more complicated though because you don't know ahead of time how many data points you'll have to go through before you find `k` that have passed the filter. It's relevant for my uses because my data points are classified and I want to find the closest `k` for a point outside of its assigned class. There are other common use cases as well - for example Theiler windows in time series analysis. Basically it boils down to excluding the data points you know *a priori* will be close to your query in order to focus on the unexpected ones.

This is implemented in other nearest-neighbor libraries, like [`NearestNeighbors.jl`](https://github.com/KristofferC/NearestNeighbors.jl).

**Comment by jlumpe** [comment]
Tests implemented, so should be good to merge if you think it's appropriate.

**Comment by altre** [comment]
Makes sense to me. Thanks for the PR.

**Pull request merged**
